### PR TITLE
Turn off hydraulic failure mortality in frozen soils

### PR DESCRIPTION
**Pull request by JessicaNeedham**
This PR address issue #1105 and turns off hydraulic failure mortality when soils are freezing, specifically, when any soil layer is below -2 degrees C. This should prevent high mortality of vegetation at high latitudes.  

### Collaborators:
@rosiealice @ckoven 

### Expectation of Answer Changes:
This is an answer changing fix - hydraulic failure will be reduced at high latitudes. 

### Checklist

*If this is your first time contributing, please read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/main/CONTRIBUTING.md) document.*

All checklist items must be checked to enable merging this pull request:

*Contributor*
- [x] The in-code documentation has been updated with descriptive comments
- [x] The documentation has been assessed to determine if updates are necessary

*Integrator*
- [x] FATES PASS/FAIL regression tests were run
- [x] Evaluation of test results for answer changes was performed and results provided

### Documentation

- [Technical Note](https://github.com/NGEET/fates-docs) update: https://github.com/NGEET/fates-docs/pull/61
- [User's Guide](https://github.com/NGEET/fates-users-guide) update: 

### Test Results:

I haven’t tested with the latest commits from main. I branched from FATES a3048a646 (E3SM b8be65d). The figure  below is compared with FATES  a3048a646. It's a no comp run - mean over year 10. 
Screenshot 2023-11-04 at 16 51 41

### CODE REVIEW

**Comment by glemieux** [comment]
This looks good.  There was a request to look at vegetation carbon results, but regardless looks good.

**Comment by JessicaNeedham** [comment]
Here's VEG C for the two high latitude PFTs. Biomass is higher with the reduction in hydraulic failure mortality. It's not a huge difference but I only ran these simulations for  10 years - this is the mean over year 10. 

Screenshot 2023-11-06 at 14 06 40

**Review by rosiealice — APPROVED** [review]
This looks fine to me.

**Comment by glemieux** [comment]
Regression testing on cheyenne is underway.

**Comment by glemieux** [comment]
Regression testing is complete.  There are multiple DIFFs against the `fates-sci.1.68.3_api.31.0.0-ctsm5.1.dev153` baseline, which is to be expected as this is answer changing, although the set of tests failing baseline comparison is smaller than I was anticipating:
```
DIFF ERS_Lm13.f10_f10_mg37.I2000Clm50Fates.cheyenne_gnu.clm-FatesCold
DIFF ERS_D_Ld15.f45_f45_mg37.I2000Clm50FatesRs.cheyenne_intel.clm-FatesColdTreeDamage
DIFF ERS_Ld60.f45_f45_mg37.I2000Clm50FatesCruRsGs.cheyenne_intel.clm-FatesColdLogging
DIFF ERS_Ld60.f45_f45_mg37.I2000Clm50FatesCruRsGs.cheyenne_intel.clm-FatesColdNoFire
DIFF ERS_Ld60.f45_f45_mg37.I2000Clm50FatesCruRsGs.cheyenne_intel.clm-Fates
DIFF ERS_Lm13.f45_f45_mg37.I2000Clm50Fates.cheyenne_intel.clm-FatesColdNoComp
DIFF ERS_P144x1_Lm25.f10_f10_mg37.I2000Clm51Fates.cheyenne_intel.clm-FatesColdNoComp
DIFF SMS_Lm6.f45_f45_mg37.I2000Clm50FatesCruRsGs.cheyenne_intel.clm-Fates
```
Parsing the output, it looks like aside from the `TreeDamage` testmod, the differences aren't triggered until just over 30 days into a run.  Of the long term tests that are passing, the `Ld60` tests make sense given that prescribed physics keeps `hmort` zero and ST3 bypasses all mortality (and other dynamics).  The single site long term tests passing B4B is reasonable given that the site is in the tropics.  As such, this looks good to go.

Location: `/glade/u/home/glemieux/scratch/ctsm-tests/tests_pr1115-fates`

**Pull request merged**
