### PR TITLE
WIP: Solar radiation unit test

### PR DESCRIPTION
**Pull request by adrifoster**
I'm at the point where it would be great to get feedback on this testing framework.

### Description:

I have created a test (not really a unit test, but similar) for running the `PatchNormanRadiation` scheme with just some input patch conditions and PFT optical parameters. At this point I think I need feedback on:

1) how to make this more useful  - what outputs to plot, etc.
2) general coding best practices

CAVEATS: this probably will only work on MY computer since the CmakeLists is currently hard coding some things, but I am working on this.

### Collaborators:
@rgknox; @ekluzek; HUGE thank you to @billsacks for helping field many questions about Cmake.

### Expectation of Answer Changes:
none

### Checklist:
- [ ] My change requires a change to the documentation.
- [x] I have updated the in-code documentation .AND. (the [technical note](https://github.com/NGEET/fates-docs) .OR. the wiki) accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/master/CONTRIBUTING.md) document.
- [ ] FATES PASS/FAIL regression tests were run 
- [ ] If answers were expected to change, evaluation was performed and provided

### Test Results:
This should not affect any production code, but will run tests when ready to make sure

### CODE REVIEW

**Comment by adrifoster** [comment]
Oh this is going to look huge but it should come in *AFTER* my other PR! I did not actually change 53 files just for this unit test...

**Comment by adrifoster** [comment]
Okay so for some reason this still shows 65 files changed...which is not correct. I think if I close and then re-open this might fix it? This seems to be a documented issue with GitHub via some google searching.

**Comment by glemieux** [comment]
> Okay so for some reason this still shows 65 files changed...which is not correct. I think if I close and then re-open this might fix it? This seems to be a documented issue with GitHub via some google searching.

That's weird.  Glad it got cleared up.

**Comment by adrifoster** [comment]
Also closing this as I think this will come in with some of @rgknox's work

**Pull request closed without merging**
