### PR TITLE
Sf fuels refactor + bole harvest litter logic fix/export frac

### PR DESCRIPTION
**Pull request by huangmy**
### Description:

This pull request aims to refactor the SPITFIRE and wood harvest logic as follows:

Reorder the fuel classes in SPITFIRE to be consistent with that in other parts of FATES;
Fix a reversed logic in treating CWD contributed by directly logged trees
Add an export fraction to account for transportation losses when shipping the boles offsite

### Collaborators:

@jkshuman 
@rgknox 
@rosiealice 
@ckoven 

### Checklist:

- [x ] My change requires a change to the documentation.
- [x ] I have updated the in-code documentation .AND. (the [technical note](https://github.com/NGEET/fates-docs) .OR. the wiki) accordingly.
- [ x] I have read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/master/CONTRIBUTING.md) document.
- [ ] FATES PASS/FAIL regression tests were run
- [ ] If answers were expected to change, evaluation was performed and provided

### Test Results:

CTSM (or) E3SM (specify which) test hash-tag:

CTSM (or) E3SM (specify which) baseline hash-tag:

FATES baseline hash-tag:

Test Output:

### CODE REVIEW

**Comment by huangmy** [comment]
@rgknox, @ckoven, @rosiealice  : this is a pull request to address https://github.com/NGEET/fates/issues/489. Please take a look and let Jackie and me know your comments?

**Comment by rgknox** [comment]
@huangmy and @jkshuman, does the index in this burned_frac_litter need to be changed?

https://github.com/NGEET/fates/blob/master/biogeochem/EDPatchDynamicsMod.F90#L1088

**Comment by jkshuman** [comment]
good catch @rgknox . Yes, that should be updated to just "c" as the refactor makes the "+1" unnecessary.

**Comment by rgknox** [comment]
will submit a PR to @huangmy 's branch with some small changes. 
1) will fix that (c+1) index
2) will move the export_fraction to be a local constant instead of parameter from file, and will stage the additional parameter in the parameter file to be added along with a group of other additions in a later PR

**Comment by huangmy** [comment]
Sounds good. Thanks!

**Comment by rgknox** [comment]
I'm going to run a multi-decade 10x10 test on this branch (with logging events on) to make sure that there are no lingering carbon balance errors.  Will check back in.

**Comment by rgknox** [comment]
@jkshuman and @huangmy : At the time of writing this I am still generating mass conservation errors following logging events.  I see no evidence suggesting that the new changes are causing these imbalances, from what I can tell these have been there for a while.
Would you like to :
a) proceed with integrating these changes (since they contain non-logging updates as well), thus fixing the mass imbalance in a later PR, or
b) wait and see if the mass balance errors can be resolved and pushed through with this set of changes

**Comment by jkshuman** [comment]
@rgknox I think digging in and fixing the mass conservation errors before incorporating these changes is best plan.

**Comment by rgknox** [comment]
Thinking more on this, I agree. Lets get this fixed before we proceed. I will look into this as well.
Labeling as "not ready".

**Comment by rgknox** [comment]
Trying to solve this remaining carbon balance error.  I believe the non-disturbance side of things is ok. I think the problem is a disconnect between litter generation and the number of trees killed during the logging disturbance portion of the code.
Here is a potential disconnect:

In this part of the code we are calculating the number of dead in lower canopy layers due to impacts from falling trees above (from logging), this number is just used to generate mortal litter flux:
https://github.com/NGEET/fates/blob/12a6c7ea35b9cd390051d1590ebb49420d3fc0fd/biogeochem/EDLoggingMortalityMod.F90#L323

Here is where we actually reduce the number density of understory trees due to impacts:
https://github.com/NGEET/fates/blob/12a6c7ea35b9cd390051d1590ebb49420d3fc0fd/biogeochem/EDPatchDynamicsMod.F90#L761

In the prior, we do not seem to be scaling the understory litter generation by this "currentPatch%fract_ldist_not_harvested" scaler.

I also think there is a disconnect in calculating that fract_ldist_not_harvested variable, as we are not filtering out grasses.

**Comment by rgknox** [comment]
Another thing I am grappling with:
currentPatch%fract_ldist_not_harvested is the fraction of the newly disturbed patch that is associated with "degredation", but not actually area opened by falling trees right?  

If this value is zero, then we assume all the area in the newly created patch is associated with falling trees, that would make the understory impact mortality rate increase (to the full value of the impact parameter).  If this value was 1, that means nothing was actually falling on the trees below, and I would assume that the understory impact morality would decrease (to zero).  But, we are actually doing the opposite here:
 https://github.com/NGEET/fates/blob/12a6c7ea35b9cd390051d1590ebb49420d3fc0fd/biogeochem/EDPatchDynamicsMod.F90#L762

I think that the currentPatch%fract_ldist_not_harvested  just needs to be encased with a (1-currentPatch%fract_ldist_not_harvested ).

**Comment by huangmy** [comment]
@rgknox @ckoven @jkshuman : I just merged Ryan's changes to fix the mass balance problem to the branch. Please test and review again.

**Comment by rgknox** [comment]
great!  I think Cheyenne is down for maintenance this week though... It will be at least a few days before we can final tests completed and integrate.

**Comment by rgknox** [comment]
@jkshuman and @huangmy , I'm having trouble getting comparable output on this branch against previous test output.  Aside from changes to the logging module, is this PR answer changing?

**Comment by huangmy** [comment]
@rgknox for the changes in the logging module, the fix to the reversed bole harvest logic should change the truck product only. However, the export fraction (set at 0.9 right now) would allow more boles left on site as CWDs. An easy test would be to set export fraction to 1.0 to see if it could match previous outputs.

I will let @jkshuman comment on the sf fuel refactoring.

**Comment by jkshuman** [comment]
@rgknox it looks like there is a mistake in the parameter ordering for the refactor for max_decomp. It was correct on my commit https://github.com/NGEET/fates/pull/523/commits/f95b44874d23b249d6ca221fd19fb45477d0ff53
checking over the params now.

**Comment by huangmy** [comment]
@jkshuman I might have made a mistake when enter them manually. Thanks for checking.

**Comment by jkshuman** [comment]
@rgknox not sure if I am reading this wrong. If I look at the files changes, it looks like it was updated correctly, but if I look at mid level commits it was correct and then wrong. Please confirm the correct order as:
fates_max_decomp = 0.52, 0.383, 0.383, 0.19, 1, 999 ;

I do not expect it to be answer changing.

**Comment by jkshuman** [comment]
@huangmy I made the same mistake myself, so the reason for my multiple commits to the param file. pesky decomp.

**Comment by rgknox** [comment]
I can confirm that is the order in the parameter file.

**Comment by huangmy** [comment]
@jkshuman I feel much better now :-).

**Comment by rgknox** [comment]
@jkshuman found the problem that was preventing b4b comparisons. I now get b4b comparisons against the baseline.

Note that in the tests,  there is a false positive, where  FUEL_MOISTURE_NFSC reports an error.  As far as I can tell, since this variable is evaluated over the fire fuel dimension, and since those positions have changed, the values in the different positions should now change.

```
FUEL_MOISTURE_NFSC   (lon,lat,fates_levfuel,time)  t_index =      2     2
       5700    19872  (    67,     5,     5,     1) (     1,     1,     1,     1) (    67,     5,     5,     1) (    11,    20,     5,     1)
                8796   2.473892450332642E+00          0.000000000000000E+00 7.2E-01  2.473892450332642E+00 8.1E-02  2.470947265625000E+00
                8796   2.473892450332642E+00          0.000000000000000E+00          1.752644181251526E+00          1.750557541847229E+00
               19872  (    67,     5,     1,     1) (     1,     1,     1,     1)
          avg abs field values:    1.270223498344421E+00    rms diff: 2.7E-01   avg rel diff(npos):  8.1E-02
                                   1.270230531692505E+00                        avg decimal digits(ndif):  1.0 worst:  0.5

```

https://github.com/NGEET/fates/blob/master/main/FatesHistoryInterfaceMod.F90#L2256

Test directory:
/gpfs/fs1/scratch/rgknox/clmed-tests/SF-refactors-merged-1.26.3-v2-C6767148-Fe90ae2f.fates.cheyenne.intel/

**Comment by rgknox** [comment]
@glemieux , I will submit a PR to @huangmy 's branch with the fix, once this is updated in this branch, I recommend we merge

**Comment by glemieux** [comment]
Roger that @rgknox

**Pull request merged**
