### PR TITLE
Fire edge-case bugfix

### LINKED ISSUE #1165: edge case in fire code causing divide by zero failure
I ran into what I believe is a weird edge in the fire code during a long global 4x5 spinup case, which is that it is possible to have only trunk mass as a fuel on a given patch, and under this condition the model generates a divide by zero error and crashes.  the first indications I got were this:

```
256: PIO: FATAL ERROR: Aborting... An error occured, Writing variables (number of variables = 419) to file (./fates_e3sm_perlmttr_fullmodel_4x5_test_landuse_nocomp_startfrompotentialveg_0005_bgcpostadspinup_v3_5aba095862_7dcb5ef1.elm.h0.0014-09.nc, ncid=294) using PIO_IOTYPE_PNETCDF iotype failed. 
Non blocking write for variable (FATES_FIRE_INTENSITY, varid=141) failed (Number of subarray requests/regions=1, 
Size of data local to this process = 1152). 
NetCDF: Numeric conversion not representable (err=-60). 
Aborting since the error handler was set to PIO_INTERNAL_ERROR... (/global/u2/c/cdkoven/E3SM/externals/scorpio/src/clib/pio_darray_int.c: 395)
256: Obtained 10 stack frames.
```

turning on debug mode led me to this:
```
127: forrtl: error (73): floating divide by zero
127: Image              PC                Routine            Line        Source             
127: libpthread-2.31.s  00001478E1DF2910  Unknown               Unknown  Unknown
127: e3sm.exe           0000000003F3DCB8  sfmainmod_mp_char         298  SFMainMod.F90
127: e3sm.exe           0000000003F39B45  sfmainmod_mp_fire         105  SFMainMod.F90
127: e3sm.exe           00000000035F9303  edmainmod_mp_ed_e         219  EDMainMod.F90
127: e3sm.exe           0000000000B06F97  elmfatesinterface        1149  elmfates_interfaceMod.F90
127: e3sm.exe           00000000009B6A3C  elm_driver_mp_elm        1288  elm_driver.F90
127: e3sm.exe           0000000000937F7C  lnd_comp_mct_mp_l         514  lnd_comp_mct.F90
127: e3sm.exe           0000000000491EEB  component_mod_mp_         757  component_mod.F90
127: e3sm.exe           000000000045327B  cime_comp_mod_mp_        2911  cime_comp_mod.F90
127: e3sm.exe           000000000047A81E  MAIN__                    153  cime_driver.F90
127: e3sm.exe           000000000041D23D  Unknown               Unknown  Unknown
127: libc-2.31.so       00001478E1C1A24D  __libc_start_main     Unknown  Unknown
127: e3sm.exe           000000000041D16A  Unknown               Unknown  Unknown
```

I have a fix that seems to work (PR coming up next). I discussed with @adrifoster about whether this is a plausible edge case to occur in the first place, and she suggested that it could maybe happen under the case that very dry fuels could burn off all fuels other than trunk, leaving only trunk fuel as a result. It seems that it is only happening in a few gridcells in Australia, so that seems consistent with the hypothesis.

### PR DESCRIPTION
**Pull request by ckoven**
This fixes the crashing situation that can occur if all fuels on a patch are trunk.

### Description:
Fixes #1165.
The solution is to just put in large-branch fuel properties if all fuels are trunk.

### Collaborators:
Discussed with @adrifoster, @glemieux, and @rgknox 

### Expectation of Answer Changes:
Shouldn't be answer changing as I don't think a test is likely to run into this situation.

### Checklist

*If this is your first time contributing, please read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/main/CONTRIBUTING.md) document.*

All checklist items must be checked to enable merging this pull request:

*Contributor*
- [x] The in-code documentation has been updated with descriptive comments
- [x] The documentation has been assessed to determine if updates are necessary

*Integrator*
- [ ] FATES PASS/FAIL regression tests were run
- [ ] Evaluation of test results for answer changes was performed and results provided

### Documentation

- [Technical Note](https://github.com/NGEET/fates-docs) update:
- [User's Guide](https://github.com/NGEET/fates-users-guide) update: 

### Test Results:

*CTSM (or) E3SM (specify which) test hash-tag:*

*CTSM (or) E3SM (specify which) baseline hash-tag:*

*FATES baseline hash-tag:*

*Test Output:*

### CODE REVIEW

**Comment by rgknox** [comment]
@ckoven , for the dummy values used when the litter is all trunk, can you confirm that these values have no impact  because they are being multiplied by zeros (or something to that effect)?

**Review by adrifoster — COMMENTED** [review]
I think this is good for now. I am working on refactoring this part of the code, so it will probably look quite different, but I will make sure to put in some checks like this as well.

**Review by adrifoster — APPROVED** [review]

**Comment by rgknox** [comment]
@adrifoster is this PR still good to go, considering the trunk fixes you implemented a couple weeks back? If yes, I think we should get this integrated

**Comment by adrifoster** [comment]
Yep this should still be fine!

**Comment by rgknox** [comment]
tests pass, tests_0426-092322de

**Pull request merged**
