### PR TITLE
Add new history output dimension patch age x fuel size class

### PR DESCRIPTION
**Pull request by glemieux**
This PR adds a new patch age x fuel size class multiplexed output dimension and includes and new history output variable `FUEL_AMOUNT_AGEFUEL` that utilizes this dimension.

### Description:
This request came out of the California LDRD meeting where the desire to be able to track the per fuel class accumulation since a given disturbance.  The corresponding CTSM side PR is https://github.com/ESCOMP/CTSM/pull/1220.

A PR to ctsm_py has been created to update to the the fates_xarray_funcs module to include an `fates_levagefuel` expansion function: https://github.com/NCAR/ctsm_python_gallery/pull/35

### Collaborators: 
@ckoven @JessicaNeedham @rgknox 

### Expectation of Answer Changes:
No answer changes expected

### Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the in-code documentation .AND. (the [technical note](https://github.com/NGEET/fates-docs) .OR. the wiki) accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/master/CONTRIBUTING.md) document.
- [x] FATES PASS/FAIL regression tests were run
- [ ] If answers were expected to change, evaluation was performed and provided

### Test Results:
TBD

CTSM (or) E3SM (specify which) test hash-tag:

CTSM (or) E3SM (specify which) baseline hash-tag:

FATES baseline hash-tag:

Test Output:

### CODE REVIEW

**Comment by glemieux** [comment]
A simple jupyter notebook looking at simple 1 year f10 grid case is available here: https://github.com/glemieux/fates-jupyter/blob/master/california/new-dimension-age_by_fuel.ipynb

**Review by ckoven — APPROVED** [review]
@glemieux this looks great.  i also ran a case with it and output looks reasonable.  thanks for adding the xarray unrolling function in https://github.com/NCAR/ctsm_python_gallery/pull/35 as well!

**Comment by rgknox** [comment]
looks good @glemieux , couldn't find any issues

**Review by rgknox — APPROVED** [review]

**Comment by glemieux** [comment]
Thanks @rgknox.  I'll run the regression tests today.

**Comment by glemieux** [comment]
Regression tests are all PASS, with exception due to baseline comparison.  During baseline comparison it appears that `cprnc` is crashing during the DIFF due to the new dimension.

**Comment by glemieux** [comment]
I reran the cprnc tool using the version that Bill fixed with https://github.com/ESMCI/cime/pull/3663.  All tests pass B4B:
```
/glade/u/home/glemieux/scratch/clmed-tests/basegen.fates-sci.1.43.2_api.14.2.0-fates_main_api_14.0.0-C0392347e-F86e8f11c
```

**Comment by glemieux** [comment]
Reran the `cprnc` tool from the cime fix in PR https://github.com/ESMCI/cime/pull/3663.  All expected pass B4B:
```
/glade/u/home/glemieux/scratch/clmed-tests/basegen.fates-sci.1.43.2_api.14.2.0-fates_main_api_14.0.0-C0392347e-F86e8f11c
```
Note that the `cs.status` script pulls from the `TestStatus` log and as such will not correctly report the manual run `cprnc` tests.

**Pull request merged**
