### PR TITLE
Update PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by ckoven**
Slight rewording to PR template revisions

### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the in-code documentation .AND. (the [technical note](https://github.com/NGEET/fates-docs) .OR. the wiki) accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/master/CONTRIBUTING.md) document.
- [ ] FATES PASS/FAIL regression tests were run
- [ ] If answers were expected to change, evaluation was performed and provided

### Test Results:

CTSM (or) E3SM (specify which) test hash-tag:

CTSM (or) E3SM (specify which) baseline hash-tag:

FATES baseline hash-tag:

Test Output:

### CODE REVIEW

**Comment by ckoven** [comment]
Thanks @glemieux. Can that package handle an either/or checkbox case as in my proposed revision here?

**Comment by glemieux** [comment]
@ckoven it looks like not yet based on this issue: https://github.com/stilliard/github-task-list-completed/issues/21.  Based on that, I think I would modify thius PR to add a "Documentation" subsection that we ask people to fill out with either the url or a comment stating no update necessary.  Then the checklist button could become a directive to respond to that subsection (which is similar to what we do for the "Testing" subsection now):

```
### Checklist
<!--- Go over all the following points, and put an `x` in all the boxes that apply. -->
<!--- If you're unsure about any of these, don't hesitate to ask. We're here to help! -->
*If this is your first time contributing, please read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/main/CONTRIBUTING.md) document.*

All checklist items must be checked to enable merging this pull request:
- [ ] The in-code documentation has been updated with descriptive comments
- [ ] The documentation has been assessed to determine if updates are necessary
- [ ] FATES PASS/FAIL regression tests were run
- [ ] Evaluation of test results for answer changes was performed and results provided

### Documentation
<!--- If this pull requests warrants an update to the tech doc or user's guide, and said changes have been made paste a link to the documentation pull request below.  ->
<!--- If documentation updates are needed, but changes do not yet have their own separate pull request, please create an issue on either repo so that we can keep track of necessary updates.->
- [Technical Note](https://github.com/NGEET/fates-docs):
- [User's Guide](https://github.com/NGEET/fates-users-guide): 
```

**Comment by glemieux** [comment]
I only just realized that this is a PR to my PR :facepalm:.

**Comment by glemieux** [comment]
@ckoven I updated the original PR with the changes above: https://github.com/NGEET/fates/pull/1069/files

**Comment by adrifoster** [comment]
FYI here is the CAM template for PRs

https://github.com/ESCOMP/CAM/blob/main/.github/ISSUE_TEMPLATE/enhancement_request.yml

**Comment by glemieux** [comment]
Thanks @adrifoster

**Comment by glemieux** [comment]
> FYI here is the CAM template for PRs
> 
> https://github.com/ESCOMP/CAM/blob/main/.github/ISSUE_TEMPLATE/enhancement_request.yml

It looks like this is using a [beta feature](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema) ([that's been in beta since 2021](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/)) and may only be for issue templates only right now.  I'll give this a try on my personal repo.

**Comment by adrifoster** [comment]
> > FYI here is the CAM template for PRs
> > https://github.com/ESCOMP/CAM/blob/main/.github/ISSUE_TEMPLATE/enhancement_request.yml
> 
> It looks like this is using a [beta feature](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema) ([that's been in beta since 2021](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/)) and may only be for issue templates currently. I'll give this a try on my personal repo to confirm.

Ah darn okay. thanks for checking it out.

**Comment by glemieux** [comment]
> > > FYI here is the CAM template for PRs
> > > https://github.com/ESCOMP/CAM/blob/main/.github/ISSUE_TEMPLATE/enhancement_request.yml
> > 
> > 
> > It looks like this is using a [beta feature](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema) ([that's been in beta since 2021](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/)) and may only be for issue templates currently. I'll give this a try on my personal repo to confirm.
> 
> Ah darn okay. thanks for checking it out.

I just tested this on an old private repo and can confirm the forms don't seem to work for PRs yet.  I did try the issue form version and that worked like a charm though!

**Comment by glemieux** [comment]
Closing after incorporating https://github.com/NGEET/fates/pull/1069/commits/397d8227712509b1e3c029f1070190e3b24db131 into #1069.

**Pull request closed without merging**
