### PR TITLE
Change all 'hite' to 'height'

### PR DESCRIPTION
**Pull request by JessicaNeedham**
This PR changes all occurrences of ‘hite’ in FATES to ‘height’. There are no changes for users since it was already correct in the parameter file and history outputs. 

At the software meeting today there seemed to be some fond feelings towards this historical quirk but no strong objections to fixing it.

### Expectation of Answer Changes:
No changes to users. Should be bfb. 

### Checklist

*If this is your first time contributing, please read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/main/CONTRIBUTING.md) document.*

All checklist items must be checked to enable merging this pull request:

*Contributor*
- [x] The in-code documentation has been updated with descriptive comments
- [x] The documentation has been assessed to determine if updates are necessary

*Integrator*
- [x] FATES PASS/FAIL regression tests were run
- [x] Evaluation of test results for answer changes was performed and results provided

### Documentation

- [Technical Note](https://github.com/NGEET/fates-docs) update: https://github.com/NGEET/fates-docs/pull/59
- [User's Guide](https://github.com/NGEET/fates-users-guide) update: 

### Test Results:

*CTSM (or) E3SM (specify which) test hash-tag:*

*CTSM (or) E3SM (specify which) baseline hash-tag:*

*FATES baseline hash-tag:*

*Test Output:*

Compiles and runs on Perlmutter CPU.

### CODE REVIEW

**Comment by rosiealice** [comment]
I am cool with this, although I will miss it slightly.

**Comment by rgknox** [comment]
I'm going to need some time sort through my feelings

**Comment by aswann** [comment]
This gives me flashbacks to some very frustrated times greping to figure out how height was calculated in ED2. It only took 13 years to change it!

**Review by rgknox — APPROVED** [review]
Changes are straight forward, I did a double check through the code, things look good, thanks @JessicaNeedham

**Comment by glemieux** [comment]
During regression testing a ran into a weird `pio` issue across all tests (including the one lone ctsm only testmod).  I suspect this was a cheyenne glitch.  I've double checked that the baseline runs fine.  I'm running a single `AllVars` case again to confirm my suspicions.

**Comment by glemieux** [comment]
After fixing another `hite` variable that came in with deconflicting against the latest tags, I was able to successfully re-run the regression tests.  All expected tests passed b4b.

cheyenne results: `/glade/u/home/glemieux/scratch/ctsm-tests/tests_pr1091-hitefix`

**Pull request merged**
