### PR TITLE
Kumarathunge et al 2019 photosynthetic temperature acclimation

### PR DESCRIPTION
**Pull request by ckoven**
This PR adds the Kumarathunge et al 2019 parameterization for photosynthetic temperature acclimation.

### Description:
This uses both a short-term and a long-term running mean temperature to allow Vcmax and Max to acclimate to local temperature conditions.  
Manuscript describing the model is https://nph.onlinelibrary.wiley.com/doi/10.1111/nph.15668

### Collaborators:
@czarakas wrote the initial version of this a while ago, in discussion with @Qianyuxuan. All I did was merge it up to a recent FATES main and integrate @rgknox's running-mean methods from #724, which are also used in #931, into it. Further discussion with @aswann @alistairrogers @walkeranthonyp @serbinsh @rosiealice @rgknox @jenniferholm @glemieux and probably others.

### Expectation of Answer Changes:
Currently the code is default-off, but if turned on, then will be answer-changing.  The switch to activate it is to set `fates_leaf_photo_tempsens_model` in the parameter file to a value of 2 (default is 1 currently).

### Checklist:

- [x] My change requires a change to the documentation.
- [ ] I have updated the in-code documentation .AND. (the [technical note](https://github.com/NGEET/fates-docs) .OR. the wiki) accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/master/CONTRIBUTING.md) document.
- [ ] FATES PASS/FAIL regression tests were run
- [ ] If answers were expected to change, evaluation was performed and provided

### Test Results:
Not yet tested.

CTSM (or) E3SM (specify which) test hash-tag:

CTSM (or) E3SM (specify which) baseline hash-tag:

FATES baseline hash-tag:

Test Output:

### CODE REVIEW

**Comment by ckoven** [comment]
Brief update: I ran the code with and without the code from this PR active, in SP mode for 15 years to see what the first-order effects of this on the global runs would be.  Attached a few figures showing the GPP change for the last ten years of the run.  Looks like it acts to increase GPP everywhere, with the relative change larger for cold than warm ecosystems.

image
image
image
image

**Comment by aswann** [comment]
Ohh, neat! Thanks for doing this Charlie!

Sent from a mobile device.
________________________________

**Comment by alistairrogers** [comment]
Great to see this make it into FATES thanks for sharing Charlie

**Comment by glemieux** [comment]
Regression testing on cheyenne is complete.  All expected tests returned B4B against `fates-sci.1.64.3_api.25.2.0-ctsm5.1.dev118`.  There are `NLCOMP` differences due to the updated parameter file reference and `FIELDLIST` differences for the test mods that include the new history output that have been added by this PR.

Cheyenne folder: `/glade/scratch/glemieux/ctsm-tests/tests_pr984`

**Review by glemieux — APPROVED** [review]

**Comment by glemieux** [comment]
I ran the fates suite with `photo_tempsens_model=photosynth_acclim_model_kumarathunge_etal_2019` to make sure that all test cases would build and run successfully.  I did not compare against the baseline since we know there will be DIFFs.  All expected test modes built and ran successfully.

Cheyenne folder: `/glade/scratch/glemieux/ctsm-tests/tests_pr984-mode2`

**Pull request merged**
