### PR TITLE
Remove Lasslop wind effect on fire ROS

### PR DESCRIPTION
**Pull request by jkshuman**
Remove reducing effect of high winds based on Lasslop et al 2014

### Description:
Within SFMain remove the conditional clause that reduces fire rate of spread for high wind speeds. Within parameter files removed the parameter for fire_wind_max that triggers the conditional.
This showed an improvement in mode simulated fire behavior in past work (Lasslop et al 2014), but current research demonstrates there is not a clear link between high winds and a reducing effect on rate of spread. Andela et al 2018 ESSDD https://doi.org/10.5194/essd-2018-89 
This PR acts to remove this Lasslop et al (2014) reducing effect, and revert back to original Thonicke ROS wind effect.

### Collaborators:
JKShuman, RKnox

### Expectation of Answer Changes:
Fire behavior rate of spread will be higher at high winds within simulation, dependent on previous fire_wind_max parameter and forcing data.

### Checklist:

- [ ] My change requires a change to the documentation.
- [x ] I have updated the in-code documentation .AND. (the [technical note](https://github.com/NGEET/fates-docs) .OR. the wiki) accordingly.
- [ x] I have read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/master/CONTRIBUTING.md) document.
- [ ] FATES PASS/FAIL regression tests were run
- [ ] If answers were expected to change, evaluation was performed and provided

### Test Results:
Code compiles and runs on Hobart.

### CODE REVIEW

**Comment by rosiealice** [comment]
Looks good to me. Do you think there should be a comment to the effect that this option exists in the literature but we've chosen to not use it for the reasons you describe!

**Comment by jkshuman** [comment]
Thanks for looking this over. I think the information in the PR as to the removal is enough.

**Comment by rgknox** [comment]
running tests

**Comment by rgknox** [comment]
All pass:
/gpfs/fs1/scratch/rgknox/clmed-tests/fates.cheyenne.intel.rem-laslop-C5dc7f0a-F34f580c

**Pull request merged**
