### PR TITLE
sorting logic changed to better handle equal-sized cohorts and to sort based on height

### PR DESCRIPTION
**Pull request by ckoven**
### Description:
This PR changes the sorting so that: 

- if using the deterministic PPA sorting algorithm, handle the special condition where two cohorts of different PFTs but the same size get demoted/promoted in proportion to their area rather than based on sorting order.
- sorting is switched to be a function of height rather than DBH.

This PR is meant to solve #438 and #302.

### Expectation of Answer Changes:
This should change answers in a few ways:

1. if 2 identical PFTs starting from bare ground are run using the strict PPA sorting algorithm, they should remain equal over time, rather than diverging.
2. if 2 non-identical PFTs are initialized to identical initial conditions using the inventory initialization, then they should actually start with the same structure rather than having some PFT-order effect thrown in.
3. if 2 PFTs with non-identical height-to-dbh allometry are competing, then their competitive dynamics will be different (and hopefully more correct)
4. in all cases when using stochastic PPA sorting algorithm, the answers should change because the promotion term is now height ** comp_excln parameter rather than dbh ** comp_excln.  To go back to the same behavior as before, it ought to work to change the comp_excln parameter by the exponent used in the height-to-dbh allometry.

### Collaborators:
discussed with @rgknox and @rosiealice.  also pinging @jenniferholm as this will effect her simulations due to point 3 above

### Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the in-code documentation .AND. (the [technical note](https://github.com/NGEET/fates-docs) .OR. the wiki) accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/master/CONTRIBUTING.md) document.
- [ ] FATES PASS/FAIL regression tests were run
- [ ] If answers were expected to change, evaluation was performed and provided

### Test Results:
not yet tested.  hold until both formal and more informal tests have been done.

CTSM (or) E3SM (specify which) test hash-tag:

CTSM (or) E3SM (specify which) baseline hash-tag:

FATES baseline hash-tag:

Test Output:

### CODE REVIEW

**Comment by ckoven** [comment]
I've updated the tech note to reflect the change in this PR: https://github.com/NGEET/fates-docs/pull/14

**Comment by rgknox** [comment]
@ckoven and I have had a good amount of back and forth on this PR, see discussion and analysis here:

https://github.com/ckoven/fates/pull/3

Will start testing

**Comment by ckoven** [comment]
Just re-discussed this with @rgknox.  We're going to hold off on merging this for a bit, as there's one thing in the change that we don't fully understand yet, which is that up until now, if you run two identical PFTs with identical initial conditions and using probabilistic sorting, they stay identical with respect to each other over time.  Something about changing from DBH-based sorting to height-based sorting is causing the model to lost that feature: with probabilistic sorting the PFTs remain very close, but no longer identical. (With deterministic sorting the ability to preserve identicalness of identical PFTs is now just as good as with probabilistic sorting, which is a good new feature and part of the motivation for this PR, but also is not perfect). We're going to stare at this a little longer and see if we can't figure out why.  If anyone else wants to take a look, please feel free.

**Comment by rgknox** [comment]
In our modeling call, @rosiealice suggested we try a test simulation where we use a very large diameter where height capping occurs, which allows us to test a hypothesis.  The premise is that height based promotion and demotion has the potential that many cohorts are at the same height, and thus a potentially large group must all be demoted together.  Height based promotion/demotion has a harder time maintaining precision and exactness between clones when it is forced to promote many of the same height, perhaps because small number densities have to be divided up more times (making very very small numbers that run into precision issues).

In this test, I set the capping height to 150000, and thus removing the chance that cohorts of different diameters would have different heights.

https://drive.google.com/file/d/1Isqo4hLiKDomEyZfo2rGxnPH4hyUz7-i/view?usp=sharing

The test shows that the large cap has no discernible improvement on maintaining parity between two cohorts with the same PFT definition.

**Comment by ckoven** [comment]
really?  I feel like that looks much closer to the first figure in https://github.com/ckoven/fates/pull/3#issuecomment-454278571 than to the other ones.  they both have the one pixel in southern africa that is not equal but otherwise significantly less than a percent error.

**Comment by rgknox** [comment]
After looking at this again, I'm realizing that the master version was not as pristine as the I remember.  And, in fact, it looks like the break down in parity between the two clones is at a smaller magnitude that what we saw in master.  
I'm going to run final tests on this, If anyone has any objections to integrating this, make your peace.

**Comment by rgknox** [comment]
See #469 regarding limited testing capabilities right now. 

Expected tests pass:
/gpfs/fs1/scratch/rgknox/clmed-tests/fates.cheyenne.intel.height-sorting-approved-v3-wrtm-Cd909f57-F2e73ba8

**Pull request merged**
