### PR TITLE
Frost mortality fix

### PR DESCRIPTION
**Pull request by mpaiao**
Bug fix for non-zero mortality at the beginning of every FATES simulation.

### Description:

Simple bug fix for the non-zero frost mortality during the first day of the simulation. The problem is that patch variable `bc_in%t_veg24_pa` is set to zero at the beginning of the simulation, and this is interpreted as zero Kelvin. My solution was to simply bypass frost mortality during the first simulation day. This fix addresses issue #781 and should have minimal impact on long-term simulations.

### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the in-code documentation .AND. (the [technical note](https://github.com/NGEET/fates-docs) .OR. the wiki) accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/master/CONTRIBUTING.md) document.
- [ ] FATES PASS/FAIL regression tests were run
- [ ] If answers were expected to change, evaluation was performed and provided

### Test Results:

CTSM (or) E3SM (specify which) test hash-tag:

CTSM (or) E3SM (specify which) baseline hash-tag:

FATES baseline hash-tag:

Test Output:

### CODE REVIEW

**Comment by rgknox** [comment]
@mpaiao , this fix might help elucidate differences I'm seeing when migrating to tracking running means on the fates side, ie #724

**Comment by mpaiao** [comment]
@rgknox I think the initial assignment for many of these "memory" variables may be worth thinking more. I see that relative humidity also starts at 0, which could exaggerate dryness for SPITFIRE too (though short-lived, just the first day).

**Comment by mpaiao** [comment]
By the way, I noticed that my 3 pull requests may need to be implemented sequentially, because I am seeing many more changes in this PR than the actual fix for mortality. I will try to organize my branches a bit better next time.

**Comment by jkshuman** [comment]
@mpaiao there is sometimes a high amount of fire in the first year. It would be great if this cleared that up. Thanks for finding and fixing this, but yes we should rethink initialization of these "memory" variables. Perhaps open a separate issue with a few examples, like the fire dependance on RH?

**Comment by glemieux** [comment]
Closing per #816

**Pull request closed without merging**
