### PR TITLE
Fixing the order in which patch-level `canopy_layer_tlai` is calculated

### LINKED ISSUE #823: Order of operations for updating `canopy_layer_tlai` can result in `treelai` value discrepencies for understory trees
### Summary

Currently, after cohort promotion/demotion, it is possible to have cohorts that have been split across canopy layers with the same `hite`, resulting in their being ordered 'next' to each other in the cohort linked list.  [In `leaf_area_profile`](https://github.com/NGEET/fates/blob/b27149270b459fc2518dc2a5bacfc48ccd256528/biogeochem/EDCanopyStructureMod.F90#L1556-L1592) we iterate through this list from tallest to smallest so as to update the patch-level `canopy_layer_tlai` for use in calculating `treelai`.  This results in an issue with calculating the understory `treelai` since the `tree_lai` function relies on the canopy layer lai above it: 

https://github.com/NGEET/fates/blob/b27149270b459fc2518dc2a5bacfc48ccd256528/biogeochem/FatesAllometryMod.F90#L622-L626

If an understory cohort is taller than other cohorts that are in the first (tallest) canopy layer, then `treelai` will be calculated too early for the understory cohort, since the value of patch-level `canopy_layer_tlai` will be incomplete for the layer above it at that point (i.e. there will be shorter height cohorts that are in the taller canopy layer that haven't had there lai calculated and added to `canopy_layer_tlai`.

### Suggested fix

Per @rgknox suggestion, simply iterating through the cohort loop twice to make sure we sum the `canopy_layer_tlai` in descending order (using a check on the `canopy_layer` value) will fix the issue.  Ryan also suggested it might be good to review where we update `tree_lai` and create a subroutine for this sort of update if this sort of update is routinely used.

### Background
While troubleshooting the SP mode ERS test restart failure in #821, I determined that the `tree_lai` and `tree_sai` function calls here:
https://github.com/NGEET/fates/blob/b27149270b459fc2518dc2a5bacfc48ccd256528/biogeochem/EDCanopyStructureMod.F90#L1986-L1997

are redundant since just prior to `update_hlm_dynamics` we run the same calls to update the patch-level area profiles:
https://github.com/NGEET/fates/blob/b27149270b459fc2518dc2a5bacfc48ccd256528/biogeochem/EDCanopyStructureMod.F90#L1567-L1576

That said, upon testing out a commit to remove these calls I found that a minority of the regression tests were not resulting in b4b outcomes, namely:
- `SMS_Lm13.1x1_brazil.I2000Clm50FatesCruRsGs.cheyenne_gnu.clm-FatesColdDef`
- `ERS_Ld60.f45_f45_mg37.I2000Clm50FatesCruRsGs.cheyenne_intel.clm-FatesColdDefLogging`

This seemed odd since the two tests don't have a lot in common, and there are other tests that have overlapping setups (i.e. length, compset, etc).  Digging into this with @rgknox help, we determined that the issue is that `treelai` can be calculated too early for understory cohorts that are taller than some top level canopy layer cohorts, due to an incomplete value of `canopy_layer_tlai`.

### PR DESCRIPTION
**Pull request by glemieux**
### Description:

This PR resolves #823.

Introduces new subroutine for potential additional future use elsewhere in the code.

### Collaborators:
@rgknox 

### Expectation of Answer Changes:
This will changes answers (although regression tests may only show this occurring in a subset of tests).

### Checklist:

- [ ] My change requires a change to the documentation.
- [x] I have updated the in-code documentation .AND. (the [technical note](https://github.com/NGEET/fates-docs) .OR. the wiki) accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/master/CONTRIBUTING.md) document.
- [ ] FATES PASS/FAIL regression tests were run
- [ ] If answers were expected to change, evaluation was performed and provided

### Test Results:
TBD

CTSM (or) E3SM (specify which) test hash-tag:

CTSM (or) E3SM (specify which) baseline hash-tag:

FATES baseline hash-tag:

Test Output:

### CODE REVIEW

**Comment by glemieux** [comment]
The refactor of the relevant `canopy_layer_tlai` section is complete (as of https://github.com/NGEET/fates/pull/828/commits/d451203d51a559ad5697d2456461ad65ebd15ea0) and was tested out against a single exact restart fates testmod on cheyenne with b4b results:
`/glade/u/home/glemieux/scratch/ctsm-tests/tests_pr828_erpshortcompare1`

Now that I'm confident the refactor is good, I'll add the additional canopy layer loop for the final fix to this issue.

**Comment by glemieux** [comment]
Talking about this with @rgknox, hes suggested reviewing the code to find other areas where we can utilize the new `UpdatePatchLAI` subroutine.  I'm going to take a look at this in the next couple days before we conduct the final regression tests.

**Comment by rgknox** [comment]
Its possible that the issue we are seeing in PR #800 could have some bearing on our methods here.

To summarize the issue, I suspect that when a large plant with lots of leaf area is demoted from the canopy to the understory (which is possible with both stochastic and rank-ordered demotion), we will encounter an "LAI explosion".  Note that in our default parameter file, several of our sla_max'es are 10x larger than sla_top.  Our algorithm assumes that when a plant is demoted to a lower layer, it is suddenly "under" all of these other leaves, which would push its mean SLA from SLA top to sla_max, thereby getting a many fold increase in SLA.

Perhaps we should modify our scheme such that plants are not influenced by canopy position, but SLA depth scaling si based more off of height?

@ckoven @glemieux @rosiealice @aswann @kovenock 

Appologies if I'm re-hashing an old issue we've debated before!

**Comment by glemieux** [comment]
Commit 1962a7d updates this branch to remove the redundant call to `tree_lai` and `tree_sai` in `update_hlm_dynamics`.

**Comment by glemieux** [comment]
Commit 1962a7d updates this branch to remove the redundant call to `tree_lai` and `tree_sai` in `update_hlm_dynamics`.

**Comment by glemieux** [comment]
6ae65be and 428d679 were manually replicated from @rgknox [coema branch](https://github.com/rgknox/fates/tree/canopy_layer_tlai-fix-coema) which is based off of this branch.  I created a [separate testing branch](https://github.com/glemieux/fates/tree/cltf-redcheck) to make sure that removing these calls truly redundant.  Said branch reverts the [3a593ad](https://github.com/NGEET/fates/pull/828/commits/3a593ad8a438c994888a877daaae24543cd5f084) to test against baseline `fates-sci.1.57.0_api.23.0.0-ctsm5.1.dev091`.  So far, the couple of regression tests are return b4b.  I will run the full fates test suite as well as a test a longer term case.

**Comment by glemieux** [comment]
Regression tests are underway.  Note that due to https://github.com/ESCOMP/CTSM/issues/1764 the `P32x2` test will come back as a run failure due to hitting the wall clock limit.

**Comment by glemieux** [comment]
I ran regression tests on Cheyenne: `/glade/u/home/glemieux/scratch/ctsm-tests/tests_pr828`

Most tests pass b4b with the following exceptions:
```
SMS_Lm13.1x1_brazil.I2000Clm50FatesCruRsGs.cheyenne_gnu.clm-FatesColdDef
SMS_Lm13.1x1_brazil.I2000Clm50FatesCruRsGs.cheyenne_intel.clm-FatesColdDef
ERS_Lm12.1x1_brazil.I2000Clm50FatesCruRsGs.cheyenne_intel.clm-FatesFireLightningPopDens
SMS_Lm6.f45_f45_mg37.I2000Clm50FatesCruRsGs.cheyenne_intel.clm-Fates
ERS_Ld60.f45_f45_mg37.I2000Clm50FatesCruRsGs.cheyenne_intel.clm-FatesColdDefLogging
```
Given the correction to the `canopy_layer_tlai` calculation, seeing differences in longer runs in which the patches can start to become more disturbed make sense.  That said, the two `SMS_Lm13.1x1_brazil` tests have differences on the first time step in `FATES_AREA_PLANTS` and `FATES_AUTORESP`.  I'm not sure yet why this is.  

Note that there are two 'known' failures right now due to #861 and https://github.com/ESCOMP/CTSM/issues/1764

**Review by rgknox — APPROVED** [review]
Looks good!

**Pull request merged**
