### PR TITLE
Define new fates_param_reader_type type to abstract HLM-side param I/O

### PR DESCRIPTION
**Pull request by johnpaulalex**
Also copy FatesReadParameters() over from CTSM. (The HLM-side ones can be deleted after they switch over to using this new one, coming next).

### Description:
FATES should not call the HLM, but currently it calls an HLM-side FatesReadParameters() which calls an HLM-side ParametersFromNetCDF() method to actually read the parameters from disk.  

With this change, FATES now has its own copy of FatesReadParameters() which takes in an HLM-provided 'fates_param_reader_type' to read the parameters from disk.  Its existing SetFatesGlobalElements1() method now takes in an optional fates_param_reader_type. Nobody passes this optional param in, yet.

Upcoming PR's will modify the HLM's to construct and pass in instances of fates_param_reader_type (which will basically call the HLM-side ParametersFromNetCDF() method), and then remove the old code path.

Associated CTSM PR: https://github.com/ESCOMP/CTSM/pull/2198
Associated E3SM PR: https://github.com/E3SM-Project/E3SM/pull/6027

[Issue ESCOMP/CTSM/2006](https://github.com/ESCOMP/CTSM/issues/2006)

### Collaborators:
adrifoster@

### Expectation of Answer Changes:
No-op; this adds a code path that isn't yet used by any HLM.

### Checklist

*If this is your first time contributing, please read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/main/CONTRIBUTING.md) document.*

All checklist items must be checked to enable merging this pull request:

*Contributor*
- [x] The in-code documentation has been updated with descriptive comments
- [x] The documentation has been assessed to determine if updates are necessary

*Integrator*
- [x] FATES PASS/FAIL regression tests were run
- [x] Evaluation of test results for answer changes was performed and results provided

### Documentation

- [Technical Note](https://github.com/NGEET/fates-docs) update: https://github.com/NGEET/fates-users-guide/issues/54
- [User's Guide](https://github.com/NGEET/fates-users-guide) update: 

### Test Results:

*CTSM (or) E3SM (specify which) test hash-tag:*
*CTSM (or) E3SM (specify which) baseline hash-tag:*
CTSM ctsm5.1.dev142

*FATES baseline hash-tag:*
fates-sci.1.67.5_api.27.0.0

*Test Output:*
(I ran the 'fates' test suite)

> sh /glade/scratch/jpalex/tests_1011-184611ch/cs.status.fails

1011-184611ch_gnu: 3 tests
    FAIL ERS_Lm13.f10_f10_mg37.I2000Clm50Fates.cheyenne_gnu.clm-FatesCold COMPARE_base_rest (EXPECTED FAILURE)

 
1011-184611ch_int: 34 tests
    PEND ERP_P72x2_Ld30.f45_f45_mg37.I2000Clm50FatesRs.cheyenne_intel.clm-mimicsFatesCold SHAREDLIB_BUILD (EXPECTED FAILURE)
    FAIL ERS_D_Ld5.1x1_brazil.I2000Clm50FatesCruRsGs.cheyenne_intel.clm-FatesColdHydro COMPARE_base_rest (EXPECTED FAILURE)
    FAIL ERS_Lm12.1x1_brazil.I2000Clm50FatesCruRsGs.cheyenne_intel.clm-FatesFireLightningPopDens COMPARE_base_rest (EXPECTED FAILURE)
    FAIL ERS_Lm13.f45_f45_mg37.I2000Clm50Fates.cheyenne_intel.clm-FatesColdNoComp COMPARE_base_rest (EXPECTED FAILURE)

### CODE REVIEW

**Review by adrifoster — APPROVED** [review]

**Comment by adrifoster** [comment]
All tests on cheyenne pass except for expected fails:

`aux_clm`:

```
1116-092112ch_int: 117 tests
    PEND ERP_P72x2_Ld30.f45_f45_mg37.I2000Clm50FatesRs.cheyenne_intel.clm-mimicsFatesCold SHAREDLIB_BUILD (EXPECTED FAILURE)

 
1116-092112ch_nvh: 3 tests
    FAIL SMS_D.f10_f10_mg37.I2000Clm51BgcCrop.cheyenne_nvhpc.clm-crop RUN time=20 (EXPECTED FAILURE)
    FAIL SMS.f10_f10_mg37.I2000Clm50BgcCrop.cheyenne_nvhpc.clm-crop RUN time=445 (EXPECTED FAILURE)
    FAIL SMS.f45_f45_mg37.I2000Clm51FatesSpRsGs.cheyenne_nvhpc.clm-FatesColdSatPhen RUN time=19 (EXPECTED FAILURE)
```

`fates`

```
1116-091452ch_gnu: 5 tests
    PASS ERS_Lm13.f10_f10_mg37.I2000Clm50Fates.cheyenne_gnu.clm-FatesCold COMPARE_base_rest (UNEXPECTED: expected FAIL)
    FAIL PEM_D_Ld15.5x5_amazon.I2000Clm50FatesRs.cheyenne_gnu.clm-FatesColdSeedDisp COMPARE_base_modpes (EXPECTED FAILURE)

 
1116-091452ch_int: 35 tests
    PEND ERP_P72x2_Ld30.f45_f45_mg37.I2000Clm50FatesRs.cheyenne_intel.clm-mimicsFatesCold SHAREDLIB_BUILD (EXPECTED FAILURE)
    FAIL ERS_D_Ld5.1x1_brazil.I2000Clm50FatesCruRsGs.cheyenne_intel.clm-FatesColdHydro COMPARE_base_rest (EXPECTED FAILURE)
    PASS ERS_Lm12.1x1_brazil.I2000Clm50FatesCruRsGs.cheyenne_intel.clm-FatesFireLightningPopDens COMPARE_base_rest (UNEXPECTED: expected FAIL)
    PASS ERS_Lm13.f45_f45_mg37.I2000Clm50Fates.cheyenne_intel.clm-FatesColdNoComp COMPARE_base_rest (UNEXPECTED: expected FAIL)
```

**Comment by adrifoster** [comment]
fates tests on izumi also pass except for expected fails:


```
1116-112732iz_nag: 8 tests
    PEND ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCruRsGs.izumi_nag.clm-FatesColdPRT2 RUN (UNEXPECTED: expected FAIL)
    FAIL ERS_D_Ld5.1x1_brazil.I2000Clm50FatesCruRsGs.izumi_nag.clm-FatesColdHydro COMPARE_base_rest (EXPECTED FAILURE)

```

**Comment by adrifoster** [comment]
`izumi` had two failing diffs for baselines but @slevis-lmwg and I think this is actually because we got new driver data for our NEON NIWOT data (which we automatically download from the NEON server for each new run) in between his `dev152` baselines yesterday and my test today

Running some tests to confirm this theory now...

**Comment by glemieux** [comment]
Thanks @adrifoster.  I've got e3sm tests going on perlmutter as well, to make sure things look ok coupling to that side.  

As an aside, it looks like #1098 fixed issues #897 and ESCOMP/CTSM#667 :tada:.  Would you mind removing those from the expected failures list?

**Comment by adrifoster** [comment]
All `fates` and `aux_clm` tests now pass!

**Pull request merged**
