### PR TITLE
comprehensive correction for singularity in two-stream

### PR DESCRIPTION
**Pull request by rgknox**
### Description:

This adds a more thorough correction to avoid singularities in the two-stream radiation. To be specific, we make sure that a correction made in the near-infrared band does not create a singularity in the visible band.

Fixes: #1276

### Expectation of Answer Changes:

Its possible but unlikely we would see differences in a test. Any test that was vulnerable would probably had failed.  This is more about future-proofing the code.

### Checklist

*If this is your first time contributing, please read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/main/CONTRIBUTING.md) document.*

All checklist items must be checked to enable merging this pull request:

*Contributor*
- [x] The in-code documentation has been updated with descriptive comments
- [x] The documentation has been assessed to determine if updates are necessary

*Integrator*
- [x] FATES PASS/FAIL regression tests were run
- [ ] Evaluation of test results for answer changes was performed and results provided

### Documentation

- [Technical Note](https://github.com/NGEET/fates-docs) update:
- [User's Guide](https://github.com/NGEET/fates-users-guide) update: 

### Test Results:

*CTSM (or) E3SM (specify which) test hash-tag:*

*CTSM (or) E3SM (specify which) baseline hash-tag:*

*FATES baseline hash-tag:*

*Test Output:*

### CODE REVIEW

**Review by glemieux — APPROVED** [review]

**Comment by glemieux** [comment]
Regression testing underway on derecho.

**Comment by glemieux** [comment]
Regression testing against `sci.1.80.1_api.37.0.0` is complete.  All expected tests pass B4B with the exception of the `FatesColdTwoStream` tests.  The difference show up on the first time step after initialization (`t_index = 2`) and appear to be round off (`< E-13`).  The following variables are different:

```
FATES_GPP
FATES_GPP_CANOPY
FATES_HET_RESP
FATES_LBLAYER_COND
FATES_MAINT_RESP
FATES_NEP
FATES_STOMATAL_COND
```

Note that of the above, only `FATES_STOMATAL_COND` and `FATES_LBLAYER_COND` are not round off.  After this time step, more differences propagate.

I decided to double check the original commit cd33abc9676b5178d5839eddbd347285f3a89abb against the baseline to make sure that my later refactor didn't inject the differences.  The results are showing the same differing variables and similar RMS values/

@rgknox I'm not sure why these particular variables would be impacted by this update.  I spot checked the baseline to make sure it was return b4b, so I'm pretty sure the issue isn't there.  Thoughts?

Results: `/glade/u/home/glemieux/scratch/ctsm-tests/tests_pr1277`

**Comment by rgknox** [comment]
THe differences in FATES_HET_RESP are kind of suspicious... That is soil respiration. I suppose radiation scattering differences could affect soil heating, which affects respiration rates. But it seems unlikely in this case?

**Comment by rgknox** [comment]
After discussing with @glemieux and getting a better sense of the magnitude of the differences, I think they fall within the realm of expectation.

**Pull request merged**
