### PR TITLE
Add logo to front page

### PR DESCRIPTION
**Pull request by ckoven**
We never added the logo that we had decided on a while ago to our GitHub repository, so here it is.

No other code changed, so no testing.

### CODE REVIEW

**Comment by glemieux** [comment]
I should piggy-back on this and add the user's guide to the Readme.

**Comment by glemieux** [comment]
@ckoven is there a version of this picture with a transparent background?

**Comment by ckoven** [comment]
> @ckoven is there a version of this picture with a transparent background?

I don't have one but you're right we should do that.  I'll either track one down or make one.

**Comment by glemieux** [comment]
I found a really large png logo from an official ngeet email.  I've uploaded the three different sized versions to a new `images` folder in the `.github` directory.

**Pull request merged**
