### PR TITLE
Zeroing a litter diagnostic that was not being zerod

### PR DESCRIPTION
**Pull request by rgknox**
### Description:

Two output variables, LITTER_IN_ELEM and LITTER_OUT_ELEM were not being zero'd inside columns (sites) prior to accumulating values. This caused their info to not be written, left as no data values.  This was causing problems for tests because these arrays had no real data and confused cprnc.

### Collaborators:

 @dqwu and @bishtgautam

### Expectation of Answer Changes:

this only effects those two diagnostics 

### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the in-code documentation .AND. (the [technical note](https://github.com/NGEET/fates-docs) .OR. the wiki) accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/master/CONTRIBUTING.md) document.
- [x] FATES PASS/FAIL regression tests were run
- [ ] If answers were expected to change, evaluation was performed and provided

### Test Results:

TBD

CTSM (or) E3SM (specify which) test hash-tag:

CTSM (or) E3SM (specify which) baseline hash-tag:

FATES baseline hash-tag:

Test Output:

### CODE REVIEW

**Comment by rgknox** [comment]
Expected pass:
/glade/scratch/rgknox/clmed-tests/fates-sci.1.33.1_api.8.1.0-clm5.0.30-C5220caaa-F26de3bbf.fates.cheyenne.intel
/glade/scratch/rgknox/clmed-tests/fates-sci.1.33.1_api.8.1.0-clm5.0.30-C5220caaa-F26de3bbf.fates.cheyenne.gnu

**Comment by jkshuman** [comment]
@rgknox I have been using an older branch, and will be moving over to master soon. Do you know if this issue has been persistent and we are just seeing it now? (I am thinking about litter feedbacks onto fire)

**Comment by rgknox** [comment]
This is just a problem with that specific diagnostic. This does not have an effect on model mechanics.

**Comment by glemieux** [comment]
This looks good to me.  Shall I merge @rgknox?

**Pull request merged**
