### PR TITLE
Initialization of NPP moving average for N fixation in E3SM

### PR DESCRIPTION
**Pull request by rgknox**
### Description:

This set of changes initializes EMA NPP correctly, which is used for nitrogen fixation. It also adds a restart term.  This is a fix.  E3SM tests have been failing in debug mode because a nan is being used.

Fixes: #1039

### Collaborators:

@glemieux 

### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the in-code documentation .AND. (the [technical note](https://github.com/NGEET/fates-docs) .OR. the wiki) accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/master/CONTRIBUTING.md) document.
- [ ] FATES PASS/FAIL regression tests were run
- [ ] If answers were expected to change, evaluation was performed and provided

### Test Results:

CTSM (or) E3SM (specify which) test hash-tag:

CTSM (or) E3SM (specify which) baseline hash-tag:

FATES baseline hash-tag:

Test Output:

### CODE REVIEW

**Review by glemieux — DISMISSED** [review]

**Comment by glemieux** [comment]
Regression testing with ctsm on cheyenne against `fates-sci.1.65.7_api.25.4.0-ctsm5.1.dev128` is complete.  All expected tests pass b4b.  Testing with e3sm is forthcoming.

Folder location: 
```
/glade/u/home/glemieux/scratch/ctsm-tests/tests_pr1041-fates
```

**Comment by glemieux** [comment]
@rgknox I created a branch off of https://github.com/E3SM-Project/E3SM/pull/5699 in which I updated the latest fates_paramfile (thanks @bishtgautam for uploading) in the namelist defaults, pointed to this branch and ran the e3sm_land_developer tests on summit.  Everything passed, although apparently there was no baseline to compare against for some reason.  

That said, I think this fix is good to integrate now.

folder location: `/ccs/home/glemieux/scratch/e3sm-tests/pr1041-pr5699.fates.summit.ibm.C7c562526f1-Fe0eb4ad4`

**Comment by glemieux** [comment]
> @rgknox I created a branch off of [E3SM-Project/E3SM#5699](https://github.com/E3SM-Project/E3SM/pull/5699) in which I updated the latest fates_paramfile (thanks @bishtgautam for uploading) in the namelist defaults, pointed to this branch and ran the e3sm_land_developer tests on summit. Everything passed, although apparently there was no baseline to compare against for some reason.
> 
> That said, I think this fix is good to integrate now.
> 
> folder location: `/ccs/home/glemieux/scratch/e3sm-tests/pr1041-pr5699.fates.summit.ibm.C7c562526f1-Fe0eb4ad4`

Double checking this with @rgknox, I realize that none of the land developer tests on summit have debug mode on, which is at issue here.  I will test with debug mode on in the near future.  This PR is on hold to integrate until then.

**Comment by glemieux** [comment]
Testing `e3sm_land_debug` on summit passed for all cases.  There didn't seem to be any baseline to compare against however, so I will see if I can test this on perlmutter for baseline comparison.

**Comment by glemieux** [comment]
Using https://github.com/rgknox/E3SM/tree/rgknox/lnd/fates-update-api, regression testing on perlmutter against `e3sm_land_developer` baseline results in b4b answers for non-fates tests.  However, the test is segfaulting during the call to `dynamics_driv`:
```
 55: Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
 55:
 55: Backtrace for this error:
 55: #0  0x149ea2389d4f in ???
 55: #1  0x552120 in __elmfatesinterfacemod_MOD_dynamics_driv
 55:    at /global/u1/g/glemieux/E3SM-project/e3sm/components/elm/src/main/elmfates_interfaceMod.F90:955
 55: #2  0x516c59 in __elm_driver_MOD_elm_drv
 55:    at /global/u1/g/glemieux/E3SM-project/e3sm/components/elm/src/main/elm_driver.F90:1290
 55: #3  0x4ffb99 in __lnd_comp_mct_MOD_lnd_run_mct
 55:    at /global/u1/g/glemieux/E3SM-project/e3sm/components/elm/src/cpl/lnd_comp_mct.F90:514
 55: #4  0x4702a8 in __component_mod_MOD_component_run
 55:    at /global/u1/g/glemieux/E3SM-project/e3sm/driver-mct/main/component_mod.F90:751
 55: #5  0x45a2ef in __cime_comp_mod_MOD_cime_run
 55:    at /global/u1/g/glemieux/E3SM-project/e3sm/driver-mct/main/cime_comp_mod.F90:2909
 55: #6  0x44de9d in cime_driver
 55:    at /global/u1/g/glemieux/E3SM-project/e3sm/driver-mct/main/cime_driver.F90:153
 55: #7  0x44de9d in main
 55:    at /global/u1/g/glemieux/E3SM-project/e3sm/driver-mct/main/cime_driver.F90:23
```

**Comment by rgknox** [comment]
Odd, I wonder if one of them is not allocated, or if the temperature in the elm structure is un-initialized?  It should be initialized at this point.  Or maybe nlevsoil is strange?

**Comment by glemieux** [comment]
Regression testing on cheyenne against `fates-sci.1.66.1_api.25.5.0-ctsm5.1.dev130` results in all expected test passing B4B.

Cheyenne folder: `/glade/u/home/glemieux/scratch/ctsm-tests/tests_pr1041-fates-dev130`

**Pull request merged**
