### PR TITLE
Update PULL_REQUEST_TEMPLATE.md

### LINKED ISSUE #1068: Update the pull request template to prompt user to make an issue for the FATES technical documentation
During our recent triage of the https://github.com/NGEET/fates-docs/issues, @ckoven suggested that we refine our PR checklist to prompt the author to at least make a new issue to track when their pull request requires an update to the technical documentation.

### PR DESCRIPTION
**Pull request by glemieux**
### Description:
Updating the PR template to direct contributors to create an issue on the fates technical and/or user's guide as necessary so that we can track what needs updating.

Resolves #1068 

### Collaborators:
@ckoven @rgknox 

### Expectation of Answer Changes:
No, as this is a github template change

### Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the in-code documentation .AND. (the [technical note](https://github.com/NGEET/fates-docs) .OR. the wiki) accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/master/CONTRIBUTING.md) document.
- [ ] FATES PASS/FAIL regression tests were run
- [ ] If answers were expected to change, evaluation was performed and provided

### Test Results:

CTSM (or) E3SM (specify which) test hash-tag:

CTSM (or) E3SM (specify which) baseline hash-tag:

FATES baseline hash-tag:

Test Output:

### CODE REVIEW

**Comment by glemieux** [comment]
Referencing comment for posterity since I meant to write it here initially: https://github.com/NGEET/fates/pull/1070#issuecomment-1692521103

**Comment by rgknox** [comment]
@glemieux I love the links to the documentation, great addition.  I think the new template is an improvement.  

Question, should we split the checklist into things that the author needs to do, and things that either the integrators (us) and/or author+integrators need to do?

**Comment by glemieux** [comment]
> @glemieux I love the links to the documentation, great addition. I think the new template is an improvement.
> 
> Question, should we split the checklist into things that the author needs to do, and things that either the integrators (us) and/or author+integrators need to do?

That's a good idea.

**Review by rgknox — APPROVED** [review]
Thanks @glemieux

**Pull request merged**
