### PR TITLE
consolidation of parameter files

### PR DESCRIPTION
**Pull request by rgknox**
### Description:

This changeset consolidates amendments to the various default parameter files into 1 parameter file. It also combines temperate and boreal cold-deciduous PFTs, and combines temperate and boreal evergreen needleaf PFTs.  It also modifies the maximum sizes of grasses to prevent them from becoming competitive with small trees for light.

This is synchronized with: 

### Collaborators:  

several, see #444 

### Sequence

This PR is synchronized with 

https://github.com/ESCOMP/ctsm/pull/676

and should create a new API tag: 7.2.0

### Special Note: 

The 3 month fates hydro test does not complete.

SMS_Lm3_D_Mmpi-serial.1x1_brazil.I2000Clm50FatesCruGs.cheyenne_intel.clm-FatesHydro.G

Getting this test passing will be added as a new high-priority issue in FATES. I am certain that changes on the fates side in PR 514 did not generate a regression. The new parameter file imposes a much more demanding simulation condition, that is why it now fails. My plan was to not add this test to the expected fails list on the fates test suite, as it should be listed as a high-priority critical issue to fix.

### Expectation of Answer Changes:

Yes, this PR should indeed change answers. This PR was designed intentionally to consolidate all answer changing parameter updates into one.

### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the in-code documentation .AND. (the [technical note](https://github.com/NGEET/fates-docs) .OR. the wiki) accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/master/CONTRIBUTING.md) document.
- [x] FATES PASS/FAIL regression tests were run
- [x] If answers were expected to change, evaluation was performed and provided

### Test Results:

CTSM (or) E3SM (specify which) test hash-tag:

CTSM (or) E3SM (specify which) baseline hash-tag:

FATES baseline hash-tag:

Test Output:

fates test suite, non-baseline, cheyenne, intel:

/gpfs/fs1/scratch/rgknox/clmed-tests/fates.cheyenne.intel.12pft-phenoff-st3-z0-orig2-C645e520-Fada3d90

50 year smoke test on f10_f10:

/gpfs/fs1/scratch/rgknox/fates-clm-tests/12pft-consolidated-merge-dp-carea-f10_f10_mg37/run

### CODE REVIEW

**Comment by ckoven** [comment]
Thanks @rgknox!  For my own (and possibly others') sanity, I tried to reverse-engineer the changes you made to make clear the differences.  So, what I did is: first sort the variables on your new default file, and the old 14-PFT default file.  Then I extracted 12 of the PFTs from the old default, via the indexswapper to get indices 1,2,4,5,6,7,9,10,11,12,13,14, to get a starting 12-pft old default file.  Then I diffed the cdl files between the new default and the old 12-PFT default, to see what actual changes have happened.  Results are below:

```
1c1
< netcdf fates_params_12pfts_sorted {
---
> netcdf fates_params_default_new_sorted {
388,393d387
< 	float fates_FBD(fates_litterclass) ;
< 		fates_FBD:units = "NA" ;
< 		fates_FBD:long_name = "spitfire parameter related to fuel bulk density, see SFMain.F90" ;
< 	float fates_SAV(fates_litterclass) ;
< 		fates_SAV:units = "NA" ;
< 		fates_SAV:long_name = "spitfire parameter related to surface area to volume ratio, see SFMain.F90" ;
396a391,393
> 	float fates_FBD(fates_litterclass) ;
> 		fates_FBD:units = "NA" ;
> 		fates_FBD:long_name = "spitfire parameter related to fuel bulk density, see SFMain.F90" ;
417a415,417
> 	float fates_SAV(fates_litterclass) ;
> 		fates_SAV:units = "NA" ;
> 		fates_SAV:long_name = "spitfire parameter related to surface area to volume ratio, see SFMain.F90" ;
589,590c589,591
< 			" Input File = /Users/cdkoven/Desktop/fates_params_14pfts_sorted.nc \n",
< 			" Indices = [1, 2, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14]" ;
---
> 			" Input File = fates_params_14pfts_031519.nc \n",
> 			" Indices = [1, 2, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14] \n",
> 			" See issue NGEET/fates issue 444" ;
597,608c598,609
<   "broadleaf_evergreen_tropical_tree                ",
<   "needleleaf_evergreen_temperate_tree              ",
<   "needleleaf_deciduous_boreal_tree                 ",
<   "broadleaf_evergreen_temperate_tree               ",
<   "broadleaf_deciduous_tropical_tree                ",
<   "broadleaf_deciduous_temperate_tree               ",
<   "broadleaf_evergreen_temperate_shrub              ",
<   "broadleaf_deciduous_temperate_shrub              ",
<   "broadleaf_deciduous_boreal_shrub                 ",
<   "arctic_c3_grass                                  ",
<   "cool_c3_grass                                    ",
<   "c4_grass                                         " ;
---
>   "broadleaf_evergreen_tropical_tree          ",
>   "needleleaf_evergreen_extratrop_tree        ",
>   "needleleaf_colddecid_extratrop_tree       ",
>   "broadleaf_evergreen_extratrop_tree         ",
>   "broadleaf_hydrodecid_tropical_tree         ",
>   "broadleaf_colddecid_extratrop_tree        ",
>   "broadleaf_evergreen_extratrop_shrub        ",
>   "broadleaf_hydrodecid_extratrop_shrub       ",
>   "broadleaf_colddecid_extratrop_shrub       ",
>   "arctic_c3_grass                            ",
>   "cool_c3_grass                              ",
>   "c4_grass                                   " ;
610c611
<  fates_alloc_storage_cushion = 2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 
---
>  fates_alloc_storage_cushion = 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 1.2, 
660,661c661
<  fates_allom_dbh_maxheight = 150, 90, 90, 90, 90, 90, 3, 3, 2, 1.47, 1.47, 
<     1.47 ;
---
>  fates_allom_dbh_maxheight = 90, 90, 90, 90, 90, 90, 3, 3, 2, 0.35, 0.35, 0.35 ;
669c669
<  fates_allom_l2fr = 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ;
---
>  fates_allom_l2fr = 0.85, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1 ;
671,672c671,672
<  fates_allom_la_per_sa_int = 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 
<     1000, 1000, 1000, 1000 ;
---
>  fates_allom_la_per_sa_int = 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 
>     0.8, 0.8, 0.8 ;
685c685
<  fates_branch_turnover = 50, 50, 50, 50, 50, 50, 50, 50, 50, 0, 0, 0 ;
---
>  fates_branch_turnover = 150, 150, 150, 150, 150, 150, 150, 150, 150, 0, 0, 0 ;
796,797c796,797
<  fates_mort_freezetol = 2.5, -55, -80, -30, 2.5, -30, -60, -10, -80, -80, 
<     -80, -80 ;
---
>  fates_mort_freezetol = 2.5, -55, -80, -30, 2.5, -30, -60, -10, -80, -80, -5, 
>     2.5 ;
838,839c838,839
<  fates_recruit_hgt_min = 1.25, 1.25, 1.25, 1.25, 1.25, 1.25, 0.75, 0.75, 
<     0.75, 0.75, 0.75, 0.75 ;
---
>  fates_recruit_hgt_min = 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 0.75, 0.75, 0.75, 
>     0.125, 0.125, 0.125 ;
841c841,842
<  fates_recruit_initd = 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 20, 20, 20 ;
---
>  fates_recruit_initd = 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 
>     0.2 ;
933,936c934,937
< fates_prt_nitr_stoich_p1 =
<   0.0047, 0.0047, 0.0047, 0.0047, 0.0047, 0.0047, 0.0047, 0.0047, 0.0047, 
<     0.0047, 0.0047, 0.0047,
<   0.0047, 0.0047, 0.0047, 0.0047, 0.0047, 0.0047, 0.0047, 0.0047, 0.0047, 
<     0.0047, 0.0047, 0.0047,
---
>  fates_prt_nitr_stoich_p1 =
>   1e-08, 1e-08, 1e-08, 1e-08, 1e-08, 1e-08, 1e-08, 1e-08, 1e-08, 1e-08, 
>     1e-08, 1e-08,
>   1e-08, 1e-08, 1e-08, 1e-08, 1e-08, 1e-08, 1e-08, 1e-08, 1e-08, 1e-08, 
>     1e-08, 1e-08,
966c967,968
< fates_turnover_carb_retrans
<   0.025, 0.025, 0.05, 0.025, 0.05, 0.05, 0.025, 0.05, 0.05, 0.05, 0.05, 0.05,
---
> fates_turnover_carb_retrans
>   0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 0.025, 
>     0.025, 0.025,
989,992d990
<  fates_FBD = 4, 15.4, 16.8, 19.6, 999, 4 ;
< 
<  fates_SAV = 66, 13, 3.58, 0.98, 0.2, 66 ;
< 
994a993,994
>  fates_FBD = 4, 15.4, 16.8, 19.6, 999, 4 ;
> 
1008a1009,1010
>  fates_SAV = 66, 13, 3.58, 0.98, 0.2, 66 ;
> 
1044,1047c1046,1053
< fates_hydr_pinot_node
<   -999, -999, -999, -999, -999, -999, -999, -999, -999, -999, -999, -999,
<   -999, -999, -999, -999, -999, -999, -999, -999, -999, -999, -999, -999,
<   -999, -999, -999, -999, -999, -999, -999, -999, -999, -999, -999, -999,
<   -999, -999, -999, -999, -999, -999, -999, -999, -999, -999, -999, -999 ;
---
> fates_hydr_pinot_node
>   -1.465984, -1.465984, -1.465984, -1.465984, -1.465984, -1.465984, 
>     -1.465984, -1.465984, -1.465984, -1.465984, -1.465984, -1.465984,
>   -1.22807, -1.22807, -1.22807, -1.22807, -1.22807, -1.22807, -1.22807, 
>     -1.22807, -1.22807, -1.22807, -1.22807, -1.22807,
>   -1.22807, -1.22807, -1.22807, -1.22807, -1.22807, -1.22807, -1.22807, 
>     -1.22807, -1.22807, -1.22807, -1.22807, -1.22807,
>   -1.043478, -1.043478, -1.043478, -1.043478, -1.043478, -1.043478, 
>     -1.043478, -1.043478, -1.043478, -1.043478, -1.043478, -1.043478 ;
1103c1109
<  fates_hydr_kmax_rsurf = 0.001 ;
---
>  fates_hydr_kmax_rsurf = 20 ;
```

Not sure why the FATES_FBD and FATES_SAV show up, but otherwise it looks as you describe it and as discussed in #444.

**Comment by rgknox** [comment]
haha, we both pretty much did the same thing, see here:

https://github.com/rgknox/fates/compare/12-pft-sorted-default...rgknox:consolidated-pft-file

**Comment by ckoven** [comment]
right, sorry for being duplicative there.

**Comment by rgknox** [comment]
No prob, sorry you did the exercise too.  I had to actually re-make this branch, and base it off of the 12-pft-sorted-default branch linked above, and then force update.  This way we can keep tweaking the parameters and the differences should track correctly.

Updated the leaf age bins to be 1.

@ckoven and others, what is your take on trying to inject more competitiveness into the parameters at this phase?  For instance, compare the tropical evergreens with the other evergreens.

**Comment by rgknox** [comment]
A few fixes were required to get the 12 PFT tests passing restart tests:

1) Phenology was turned off for ST3 simulations, which is fairly consistent with the meaning of Static Stand Structure.  When ST3 is turned on, litter fluxes and litter to bgc boundary conditions are not calculated.  So if we want to allow leaf phenology turned on with ST3, we need to code in the leaf litter fluxes.  We can leave this as a new feature to add if desired.

2) The total leaf conductance weighted by leaf area was added to restarts.  It was originaly thought that this variable was not needed by in restart because it is re-calculated during run time. But it was also needed during the BTRAN calculation, which happens before photosynthesis is called during restarts.

**Comment by jenniferholm** [comment]
This is a great effort to consolidate the multiple parameter files! Plus, there has been some good work in updating some of the parameter values themselves that seem out-of-date, or originally were a little unrealistic. 

Something I found -- we should also update fates_seed_dbh_repro_threshold from 150 to 90 to match fates_allom_dbh_maxheight, or do we want the reproduction one to be higher? 

I'm behind with responding to these threads, but I wanted to highlight in preparation for a tropical FATES publication at ZF2, I've updating some of the parameter values. I mentioned this in #513 and re-listing them here. Based on my sensitivity analysis at ZF2 these changes did improve model results compared to the benchmarking data, and model heterogeneity.

It was nice to see dbh maxheight was lowered, because I also lowered to 100. 
I also found that lowering the storage cushion helped, but I was only testing between 1.5 and 1.9 (new default is 1.2). 


Tropical evergreen PFT sensitivity testing at ZF2 = 
fates_leaf_slatop from 0.012 to 0.016
fates_leaf_vcmax25top from 50 to 45 (Walker et al. 2014; but running FATES in a 12 PFT mode, then this really makes the tropical PFT less competitive)
fates_alloc_storage_cushion from 2.0 to 1.9
fates_leaf_stor_priority from 0.8 to 0.85
fates_comp_excln from 3 to 3.3
fates_allom_dbh_maxheight from 150 to 100
fates_mort_scalar_cstarvation from 0.6 to 0.4
fates_allom_d2bl2 from 1.3 to 1.5 (The 1.3 is from Farrior et al. and I kept the original value from clm-ed)
fates_allom_d2ca_coefficient_max from 0.656 to 0.516 (due to changing fates_allom_d2bl2)
fates_allom_d2ca_coefficient_min from 0.338 to 0.2399 (due to changing fates_allom_d2bl2)
fates_seed_alloc_mature from 0 to 0.3 (I don't have data to back this up, but this addresses the issue once tree reach mature, max size they might contribute more to seeds compared to other organs. Basically this helped to dampen the very large tree bias)

**Comment by rgknox** [comment]
Thanks @jenniferholm.  
Lets get recommendations into a new thread somewhere so that they can inform our next round of parameter updates.  I just finished the final tests on this pull request and will integrate today.

**Comment by rgknox** [comment]
final tests PASS:

/gpfs/fs1/scratch/rgknox/clmed-tests/fates-s.1.26.2_a.7.2.0-Ce580a89-F518c862.fates.cheyenne.intel

**Pull request merged**
