### PR TITLE
Allow snow to occlude LAI

### LINKED ISSUE #359: ground snow is not occluding lai profile
This is a known issue, but wanted a record of it.

In EDCanopyStructureMod.F90: leaf_area_profile()

The effective and total leaf and stem area index profiles by canopy-layer x pft x leaf-layer are calculated.

The effective should be the non snow-occluded value, compared to the total.

The calculations for the exposed fractions are calculated, but currently we are forcing them to 1, probably to keep things simple for now.

Perhaps we should investigate removing the forced exposed fraction in the near future.

### PR DESCRIPTION
**Pull request by ckoven**
The snow burial logic in FATEs has been turned off for a long while because of a bug, this fixes the bug and turns it on.  This has been a known bug for a long time (#359), and was not a priority when the model was mainly being used in the tropics, but that that is no longer the case.

### Description:
There was an indexing issue in the snow occlusion logic, for partially-occluded LAI layers it was using the fraction buried rather than the fraction exposed. 

Fixes #359.
requires HLM-side changes.  
Accompanying CTSM PR is https://github.com/ESCOMP/CTSM/pull/1324.  
E3SM PR TBD.

### Collaborators:
@rgknox @rosiealice.  cc @huitang-earth @jenniferholm and anyone else using FATES in snowy ecosystems

### Expectation of Answer Changes:
expected answer-changing where there is snow, not answer changing where there is not.
tested for 60 years in three-PFT system (two trees+grass) over California.  First figure below shows the difference between total LAI and exposed LAI as a function of snow depth across the grid.  Results make sense in that more snow equals more occluded LAI.

Screen Shot 2021-03-26 at 9 32 06 AM

Second picture shows the difference in monthly-mean albedo between two runs(this branch minus master) as a function of snow depth.  Results are more scattered because full model dynamics are on, so ecosystem structures and everything else differs.  But I think this also roughly makes sense.  

Screen Shot 2021-03-26 at 9 34 15 AM

We should probably do a test of a global FATES-SP configured comparison against master.

### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the in-code documentation .AND. (the [technical note](https://github.com/NGEET/fates-docs) .OR. the wiki) accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/master/CONTRIBUTING.md) document.
- [ ] FATES PASS/FAIL regression tests were run
- [ ] If answers were expected to change, evaluation was performed and provided

### Test Results:
Not yet run through test suite.

CTSM (or) E3SM (specify which) test hash-tag:

CTSM (or) E3SM (specify which) baseline hash-tag:

FATES baseline hash-tag:

Test Output:

### CODE REVIEW

**Review by rosiealice — APPROVED** [review]
looks good to me.

**Comment by jenniferholm** [comment]
@ckoven - this is great, and thanks for going back in and allowing for these lines of code. I completely forgot about this! And I was just looking into snow depth, LAI, ect. in my boreal simulations because I was getting very high GPP. (There might be other issues leading to the high GPP, but I bet this will help.)

So would this mean that previously, before allowing for snow to occlude LAI, would elai and lai have been the same? Because I'm also getting identical elai and lai.

**Comment by ckoven** [comment]
thanks @jenniferholm! these results make sense to me given your leaf height distribution.  in my runs I had grasses active so there was some low-statured leaf area to be occluded.  in principle, I think the lack of much of a response in your run speaks to a need to incorporate canopy snow interception in FATES...

**Comment by jenniferholm** [comment]
Ok, cool. Thanks for the second set of eyes on this!  Yea, I only had the conifer trees and no grass or shrubs. 

You make a good point about including canopy snow interception. Especially up in these higher latitudes were there are lots of trees and also still lots of snow (probably covering any potential grass layer).  I second this effort!

**Comment by rgknox** [comment]
@ckoven , the exact restart regression tests on this PR are failing.  Runs are completing, but they are not comparing exactly to their base simulations.

```
clmed-tests/fates-sci.1.44.0_api.14.2.0-ctsm5.1.dev025-C2094348b-Fd9cb6f7d-snowbur.fates.cheyenne> ./cs.status.20210330_093933_4chy4e | grep FAIL
  ERP_D_Ld3.f19_g17.I2000Clm50FatesCru.cheyenne_intel.clm-FatesColdDef (Overall: FAIL) details:
    FAIL ERP_D_Ld3.f19_g17.I2000Clm50FatesCru.cheyenne_intel.clm-FatesColdDef COMPARE_base_rest
  ERP_D_P32x2_Ld3.f19_g17.I2000Clm50FatesCru.cheyenne_intel.clm-FatesColdDef (Overall: FAIL) details:
    FAIL ERP_D_P32x2_Ld3.f19_g17.I2000Clm50FatesCru.cheyenne_intel.clm-FatesColdDef COMPARE_base_rest
  ERP_Ld3.f09_g17.I2000Clm50Fates.cheyenne_intel.clm-FatesColdDef (Overall: FAIL) details:
    FAIL ERP_Ld3.f09_g17.I2000Clm50Fates.cheyenne_intel.clm-FatesColdDef COMPARE_base_rest
  ERP_Ld9.f45_f45_mg37.I2000Clm50FatesCru.cheyenne_intel.clm-FatesAllVars (Overall: FAIL) details:
    FAIL ERP_Ld9.f45_f45_mg37.I2000Clm50FatesCru.cheyenne_intel.clm-FatesAllVars COMPARE_base_rest
  ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCru.cheyenne_intel.clm-FatesPRT2 (Overall: FAIL) details:
    FAIL ERS_D_Ld30.f45_f45_mg37.I2000Clm50FatesCru.cheyenne_intel.clm-FatesPRT2 COMPARE_base_rest
  ERS_D_Ld3.f19_g17.I2000Clm50FatesCru.cheyenne_intel.clm-FatesColdDef (Overall: FAIL) details:
    FAIL ERS_D_Ld3.f19_g17.I2000Clm50FatesCru.cheyenne_intel.clm-FatesColdDef COMPARE_base_rest
  ERS_D_Ld5.1x1_brazil.I2000Clm50FatesCru.cheyenne_intel.clm-FatesHydro (Overall: FAIL) details:
    FAIL ERS_D_Ld5.1x1_brazil.I2000Clm50FatesCru.cheyenne_intel.clm-FatesHydro COMPARE_base_rest
  ERS_Ld30.f45_f45_mg37.I2000Clm50FatesCru.cheyenne_intel.clm-FatesReducedComplexFixedBiogeo (Overall: FAIL) details:
    FAIL ERS_Ld30.f45_f45_mg37.I2000Clm50FatesCru.cheyenne_intel.clm-FatesReducedComplexFixedBiogeo COMPARE_base_rest
  ERS_Ld30.f45_f45_mg37.I2000Clm50FatesCru.cheyenne_intel.clm-FatesSizeAgeMort (Overall: FAIL) details:
    FAIL ERS_Ld30.f45_f45_mg37.I2000Clm50FatesCru.cheyenne_intel.clm-FatesSizeAgeMort COMPARE_base_rest
  ERS_Ld5.f19_g17.I2000Clm45Fates.cheyenne_intel.clm-FatesColdDef (Overall: FAIL) details:
    FAIL ERS_Ld5.f19_g17.I2000Clm45Fates.cheyenne_intel.clm-FatesColdDef COMPARE_base_rest
  ERS_Ld60.f45_f45_mg37.I2000Clm50FatesCru.cheyenne_intel.clm-Fates (Overall: FAIL) details:
    FAIL ERS_Ld60.f45_f45_mg37.I2000Clm50FatesCru.cheyenne_intel.clm-Fates COMPARE_base_rest
  ERS_Ld60.f45_f45_mg37.I2000Clm50FatesCru.cheyenne_intel.clm-FatesLogging (Overall: FAIL) details:
    FAIL ERS_Ld60.f45_f45_mg37.I2000Clm50FatesCru.cheyenne_intel.clm-FatesLogging COMPARE_base_rest
  ERS_Ld60.f45_f45_mg37.I2000Clm50FatesCru.cheyenne_intel.clm-FatesNoFire (Overall: FAIL) details:
    FAIL ERS_Ld60.f45_f45_mg37.I2000Clm50FatesCru.cheyenne_intel.clm-FatesNoFire COMPARE_base_rest
  ERS_Ld60.f45_f45_mg37.I2000Clm50FatesCru.cheyenne_intel.clm-FatesPPhys (Overall: FAIL) details:
    FAIL ERS_Ld60.f45_f45_mg37.I2000Clm50FatesCru.cheyenne_intel.clm-FatesPPhys COMPARE_base_rest
  ERS_Ld60.f45_f45_mg37.I2000Clm50FatesCru.cheyenne_intel.clm-FatesST3 (Overall: FAIL) details:
    FAIL ERS_Ld60.f45_f45_mg37.I2000Clm50FatesCru.cheyenne_intel.clm-FatesST3 COMPARE_base_rest
```

**Comment by rgknox** [comment]
that seemed to fix the problem. So it appears that the snow_depth_avg is not being updated correctly at some point during a restart.

**Comment by rgknox** [comment]
It looks like both snow_depth and frac_sno_eff are part of the restart machinery on the CTSM side, however I'm noticing some subtleties in frac_sno_eff that I'm still trying to unravel:
https://github.com/ESCOMP/CTSM/blob/master/src/biogeophys/WaterDiagnosticBulkType.F90#L652-L677

**Comment by rgknox** [comment]
I  tested the effects of holding just one of two variables that build snow_depth_avg constant, and in each case, I got failures. So it seems that both variables are not being updated correctly for our case. 

The snow depth effects on LAI are called via canopy_summarization, which is called here: https://github.com/ESCOMP/CTSM/blob/master/src/utils/clmfates_interfaceMod.F90#L985-L994

Note that this routine is called for dynamics during the time-loop, cold-starts and restarts.   https://github.com/ESCOMP/CTSM/blob/master/src/utils/clmfates_interfaceMod.F90#L1405-L1407

**Comment by ckoven** [comment]
ok I've confirmed that the failure for exact restarts was because of a weird case where the daily calls to `leaf_area_profile` use as an argument the 30-minute-updated snow depth variables, which means that if the restart isn't in sync with the daily FATES call, then it would get a different value for the snow depth during the restart than it would otherwise get.  the simplest solution to this was to make a new site-level value, and on normal timestepping calls to `leaf_area_profile` just save the snow_depth term into that site-level variable, and save that site-level variable to restarts.  during restarts, instead of using the HLM-side snow depth information for `leaf_area_profile`, it can use the internal-to-FATES restart value which was saved from the day prior to the restart.  Doing that allows it to pass restart test (at least on the one test I just ran, `ERP_D_Ld3.f19_g17.I2000Clm50FatesCru.cheyenne_intel.clm-FatesColdDef`).  

but this now requires a change outside the interface to differentiate between timestepping calls and restart calls.  I have a branch with the changes in commit https://github.com/ckoven/ctsm/commit/e33f6bc and branch https://github.com/ckoven/ctsm/tree/snow_occlusion_ctsm

**Comment by rgknox** [comment]
@ckoven , these changes now pass on all the expected tests, except for one:

ERP_D_P32x2_Ld3.f19_g17.I2000Clm50FatesCru.cheyenne_intel.clm-FatesColdDef

Where I'm seeing a very ambiguous error about trying to access an unallocated pointer.  Going back running tests now on earlier branches and trying to see if we missed this on an earlier tag, or ctsm-fates tag combo.

ctsm dev029 and fates tag 1.43.2 does pass this test

**Comment by rgknox** [comment]
Strange, after re-testing today, this branch is now passing ERP_D_P32x2_Ld3.f19_g17.I2000Clm50FatesCru.cheyenne_intel.clm-FatesColdDef  ...

**Comment by rgknox** [comment]
re-ran regression tests, all expected passes are PASS:
/glade/scratch/rgknox/clmed-tests/snow-burial-fix-ctsm5.1.dev029-C86f56515-F0b83fe23.fates.cheyenne

**Review by rgknox — APPROVED** [review]

**Comment by ckoven** [comment]
I've added E3SM branch https://github.com/ckoven/E3SM/tree/ckoven/lnd/fates_snow_occlusion to provide host-side hooks for this as well.

**Comment by glemieux** [comment]
re-ran regression tests on cheyenne and all expected PASS: `/glade/u/home/glemieux/scratch/tests_0420-123907ch`

**Pull request merged**
