### PR TITLE
Update the PFT swapper tool to use double precision

### PR DESCRIPTION
**Pull request by rgknox**
### Description:

The python tool used for pulling out specific PFTs from the parameter file needs to be converted to use doubles (instead of single precision real numbers).

### Collaborators:

@JessicaNeedham

### Testing:

This tool is not covered in standard regression testing.  I did however use it to manipulate the default file, and check to see if the resulting file had all the variables, and that they were doubles.

### CODE REVIEW

**Comment by JessicaNeedham** [comment]
Looks good to me. I'd changed 'f' to 'd' and had no problem with it. I had also changed the word 'float' on line 180 to 'double' but I'm a very new python user so maybe that was unnecessary.

**Comment by rgknox** [comment]
@JessicaNeedham , yes, I think you are right, that double should be there, will fix.

**Comment by JessicaNeedham** [comment]
I added 'from numpy import *' to get that to work.

**Comment by rgknox** [comment]
Actually, double checking this, python by default uses double precision for all real types. float() actually returns a double precision variable, so we should be good to go here.

**Comment by rgknox** [comment]
This was helpful, I needed to read-up on python precision: https://docs.python.org/2/tutorial/floatingpoint.html

**Comment by JessicaNeedham** [comment]
Good to know! Thanks - I'll check out that link.

**Comment by rgknox** [comment]
I'm going to go ahead and merge this since the changes are trivial and ancillary to the base code

**Pull request merged**
