### PR TITLE
Remove TPU limitation

### LINKED ISSUE #519: Remove TPU limitation
@alistairrogers and his group have been doing some work on the lack of evidence for TPU limitation not having enough evidence to support it's inclusion in ESMs (references to follow), following on from a series of papers on the subject including the one on CLM that @danicalombardozzi led (illustrating the large sensitivity to TPU parameters under high CO2 scenarios which is perhaps not justified by data, https://iopscience.iop.org/article/10.1088/1748-9326/aacf68/pdf). 

Given that TPU calculations are done for each leaf layer of each cohort at each timestep, we could potentially save a lot of computation by removing this altogether. 

I made a branch here with the TPU statements removed from the photosynthesis code. 
https://github.com/rosiealice/fates/tree/no_TPU

@alistairrogers and @walkeranthonyp, can you check that I'm doing the new smoothing calculations correctly, here?:
https://github.com/rosiealice/fates/blob/fc77a8b8103817a0ae37fc62a887bd2cd2efb94d/biogeophys/FatesPlantRespPhotosynthMod.F90#L1053

I'll try testing the impacts of this early next week, including the time savings...

If anyone wants to put up a defence of TPU limitation, please chime in!

### PR DESCRIPTION
**Pull request by ckoven**
This PR removes TPU limitation from FATES.

### Description:
per #519, we agreed to ged rid of TPU limitation as an unnecessary thing.

### Collaborators:
@rosiealice made the initial changes, I brought things up to date.  @walkeranthonyp @alistairrogers weighed in on original motivation and implementation details

### Expectation of Answer Changes:
should be answer-changing, but with minor effects.  For a quick run I did across California, the differences were within about 1% of the main branch code.  In principle it should speed things up but in my test the effect was small (a couple percent maybe).

also removes TPU parameters from the model.  the old parameter files with the TPU parameters should still work, the TPU parameters just won't be read.

fixes #519.

### Checklist:

- [X] My change requires a change to the documentation.
- [ ] I have updated the in-code documentation .AND. (the [technical note](https://github.com/NGEET/fates-docs) .OR. the wiki) accordingly.
- [X] I have read the [**CONTRIBUTING**](https://github.com/NGEET/fates/blob/master/CONTRIBUTING.md) document.
- [ ] FATES PASS/FAIL regression tests were run
- [ ] If answers were expected to change, evaluation was performed and provided

will update the tech note accordingly and issue a PR there before this is pulled.

### Test Results:

not yet formally tested.

CTSM (or) E3SM (specify which) test hash-tag:

CTSM (or) E3SM (specify which) baseline hash-tag:

FATES baseline hash-tag:

Test Output:

### CODE REVIEW

**Comment by rosiealice** [comment]
Looks good to me @ckoven

**Review by rgknox — APPROVED** [review]
Looks good to me. I always like to see unnecessary parameters removed too!

**Comment by rgknox** [comment]
Tests pass: 

/glade/scratch/rgknox/clmed-tests/fates-sci.1.44.0_api.14.2.0-ctsm5.1.dev029-C3ac43057-Fb18d8e68.fates.cheyenne

**Comment by glemieux** [comment]
Cross referencing the odd gnu test failure: https://github.com/NGEET/fates/issues/728

**Comment by glemieux** [comment]
Ryan re-tested this using `ctsm5.1.dev025` after we determined that `ctsm5.1.dev027` is causing the one unexpected test runtime failure.  All expected tests pass b4b now: 
`/glade/scratch/rgknox/clmed-tests/fates-sci.1.43.6_api.14.2.0-ctsm5.1.dev025-C2094348b-F079ed299.fates.cheyenne`

**Pull request merged**
